-- require "busted.runner" ()

insulate("RCLootCouncil_Classic", function()
	it("can load Classic addon", function()
		local loader = loadfile("RCLootCouncil/.specs/AddonLoader.lua")()
		assert.has_no.errors(function()
			loader.LoadToc("RCLootCouncil_Classic.toc")
		end)
	end)
end)

insulate("RCLootCouncil_Classic", function()
	it("can perform login phase", function()
		local s = spy.on(_G, "_errorhandler")
		stub(_G, "UnitGUID", function(unit)
			return "Player-1-00000002"
		end)
		dofile("RCLootCouncil/.specs/AddonLoader.lua").LoadToc("RCLootCouncil_Classic.toc")
		dofile("RCLootCouncil/.specs/EmulatePlayerLogin.lua")
		assert.spy(s).was_not.called()
	end)
end)
