require "busted.runner" ()
dofile("../.specs/ClassicAddonLoader.lua").LoadToc("../RCLootCouncil_Classic.toc")
dofile("../.specs/EmulateClassicPlayerLogin.lua")

describe("#Classic #MasterLooter", function()
   it("should load", function()
		WoWAPI_FireEvent("PLAYER_ENTERING_WORLD", false, false)
		WoWAPI_FireEvent("RAID_INSTANCE_WELCOME")
		_ADVANCE_TIME(3)
		print(_G.RCLootCouncil.masterLooter)
   end)
end)