name: Release
on:
  push:
    tags:
      - "**"

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      WAGO_API_TOKEN: ${{ secrets.WAGO_API_KEY }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Clone project
        uses: actions/checkout@v3

      - name: Create changelog
        # Grabs everything under the top level # header and outputs to a new file
        run: sed -n "1p; 2,/^# / {/^# /d; p}" Changelog.md > Changes.md
      
      - name: Package and Release
        run: bash .scripts/build.sh

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: RCLootCouncil_Classic
          path: RCLootCouncil_Classic-*.zip